name: KBOT-CICD

on: 
  push:
    branches:
      - develop
env:
  TARGETOS: linux
  TARGETARCH: amd64

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test
